project:
  type: website
  output-dir: ../docs
website:
  title: testingpackage
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/joshuafayallen/testingpackage
        aria-label: testingpackage GitHub
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.qmd
      - section: Reference
        contents:
          - text: import_palmer_penguins
            file: man/import_palmer_penguins.qmd
      - text: License
        file: LICENSE.md
      - text: Citation
        file: CITATION.md
